export const DNEXUS_FILECONTRACT_DEPLOY_ADDRESS = "";
export const DNEXUS_STUDENTCONTRACT_DEPLOY_ADDRESS = "";
export const DNEXUS_SCHOOLCONTRACT_DEPLOY_ADDRESS = "";
export const DNEXUS_USERCONTRACT_DEPLOY_ADDRESS = "";